### ISSUE TITLE
Document how we support YAML anchors

### ISSUE THREAD

**Issue by le0d4v1nc1** [tauroboros/snake#13]
Snake natively supports YAML "anchors" which is a really cool feature that will prevent you from duplicating options. The reason almost all of the properties in Snake are implemented as lists is to work with anchors. By taking advantage of this feature we can encourage users to create dozens of different profiles for each platform.

Here is how they work:

```yaml
Profiles:
   - name: profile1
     flags.link:
         - &clang-link-flags -fuse-ld=mold -Wl,--no-copy-dt-needed-entries
           -Wl,--as-needed -Wl,--gc-sections -Wl,--strip-all -Wl,--no-allow-shlib-undefined
           -Wl,--unresolved-symbols=report-all -Wl,--fatal-warnings
           -Bsymbolic -Bsymbolic-functions

   - name: profile2
     flags.link:
         - *clang-link-flags
```

Check out this website: https://learnxinyminutes.com/docs/yaml/
