### ISSUE TITLE
Get rid of resource bases

### ISSUE THREAD

**Issue by le0d4v1nc1** [tauroboros/snake#47]
Only really added it to account for +directories but the added complexity it introduces outweighs its benefits. Going to get rid of it so developers can only use `prefix`.

**Comment by le0d4v1nc1** [comment]
Going to automatically handle regex sub-directories. Something like:

```yaml
- prefix: assets
  files:
    - ${CMAKE_SOURCE_DIR}/res/shaders/*
```

The prefix will be added to any directory relative to the base provided instead of just the filename. For example, `${CMAKE_SOURCE_DIR}/res/shaders/+qsb/shader.frag` becomes `assets/+qsb/shader.frag`.
